x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  whoami:
    image: traefik/whoami:v1.12.0
    container_name: whoami
    restart: unless-stopped
    logging: *logging
