x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  grafana:
    image: grafana/grafana:13.1.3
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro,Z
    networks:
      - observability
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.docker.network=proxy
    logging: *logging

  loki:
    image: grafana/loki:3.7.6
    restart: unless-stopped
    command: -config.file=/etc/loki/config.yaml
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro,Z
      - loki_data:/loki
    networks:
      - observability
    logging: *logging

  alloy:
    image: grafana/alloy:v1.18.1
    restart: unless-stopped
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro,Z
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:ro
    networks:
      - observability
    logging: *logging

volumes:
  grafana_data:
  loki_data:

networks:
  observability:
    driver: bridge
    internal: true
  proxy:
    name: proxy
    external: true
