x-logging: &logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:2.14.3-fat
    restart: unless-stopped
    environment:
      SECURITY_ENABLELOGIN: "false"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling PDF
      TZ: Europe/Ljubljana
    volumes:
      - tessdata:/usr/share/tessdata
      - config:/configs
      - logs:/logs
    logging: *logging

volumes:
  tessdata:
  config:
  logs:
